kind: pipeline
name: arm64

workspace:
  path: src/github.com/containerd/containerd

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: golang:1.11.9
  environment:
    TRAVIS_GOOS: linux
#    GOARCH: arm64
    CGO_ENABLED: 1
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v1 TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v2 TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runtime.v1.linux TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=darwin TRAVIS_CGO_ENABLED=0

# TODO: Can't do this yet
#  privileged: true

  commands:
    # Dump the configuration name into the log
  - uname -a
    # TODO: Put these into a pre-built container
  - apt-get update -y
  - apt-get install -y btrfs-tools libnl-3-dev libnet-dev protobuf-c-compiler
    python-minimal libcap-dev libaio-dev libprotobuf-c0-dev libprotobuf-dev
    socat libseccomp-dev sudo unzip
    # - protobuf-compiler

  - sudo PATH=$PATH GOPATH=$GOPATH script/setup/install-protobuf
  - sudo chmod +x /usr/local/bin/protoc
  - sudo chmod og+rx /usr/local/include/google /usr/local/include/google/protobuf /usr/local/include/google/protobuf/compiler
  - sudo chmod -R og+r /usr/local/include/google/protobuf/
  - protoc --version
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/kunalkushwaha/ltag
  - go get -u github.com/LK4D4/vndr
  - if [ "$TRAVIS_GOOS" = "linux" ]; then sudo PATH=$PATH GOPATH=$GOPATH script/setup/install-runc ; fi
  - if [ "$TRAVIS_GOOS" = "linux" ]; then sudo PATH=$PATH GOPATH=$GOPATH script/setup/install-cni ; fi
  - if [ "$TRAVIS_GOOS" = "linux" ]; then sudo PATH=$PATH GOPATH=$GOPATH script/setup/install-critools ; fi
  - if [ "$TRAVIS_GOOS" = "linux" ]; then wget https://github.com/checkpoint-restore/criu/archive/v3.7.tar.gz -O /tmp/criu.tar.gz ; fi
  - if [ "$TRAVIS_GOOS" = "linux" ]; then tar -C /tmp/ -zxf /tmp/criu.tar.gz ; fi
  - if [ "$TRAVIS_GOOS" = "linux" ]; then cd /tmp/criu-3.7 && sudo make install-criu ; fi
# cd $TRAVIS_BUILD_DIR
  - mkdir -p $HOME/build && cd $HOME/build
