kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: golang:1.11.9
  environment:
    GOOS: linux
    GOARCH: arm64
    CGO_ENABLED: 0
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v1 TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runc.v2 TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=linux TEST_RUNTIME=io.containerd.runtime.v1.linux TRAVIS_CGO_ENABLED=1
#    TRAVIS_GOOS=darwin TRAVIS_CGO_ENABLED=0

# TODO: Can't do this yet
#  privileged: true

  commands:
    # Dump the configuration name into the log
  - uname -a
    # TODO: Put these into a pre-built container
  - apt-get install -y btrfs-tools libnl-3-dev libnet-dev protobuf-c-compiler \
    python-minimal libcap-dev libaio-dev libprotobuf-c0-dev libprotobuf-dev \
    socat libseccomp-dev
    # - protobuf-compiler
